export const DATA = {
  es: {
    classes: [
      { id: "barbarian", name: "Bárbaro" },
      { id: "bard", name: "Bardo" },
      { id: "cleric", name: "Clérigo" },
      { id: "druid", name: "Druida" },
      { id: "fighter", name: "Guerrero" },
      { id: "monk", name: "Monje" },
      { id: "paladin", name: "Paladín" },
      { id: "ranger", name: "Explorador" },
      { id: "rogue", name: "Pícaro" },
      { id: "sorcerer", name: "Hechicero" },
      { id: "warlock", name: "Brujo" },
      { id: "wizard", name: "Mago" },
      { id: "artificer", name: "Artificiero" }
    ],

    subclassesByClass: {
      barbarian: [
        "Senda del Berserker",
        "Senda del Guerrero Totémico",
        "Senda de la Bestia",
        "Senda de la Magia Salvaje",
        "Senda del Guardián Ancestral",
        "Senda del Fanático",
        "Senda del Heraldo de la Tormenta",
        "Senda del Juggernaut",
        "Senda del Corazón Salvaje",
        "Senda del Árbol del Mundo",
        "Senda del Gigante"
      ],
      bard: [
        "Colegio del Conocimiento",
        "Colegio del Valor",
        "Colegio de la Danza",
        "Colegio del Glamour",
        "Colegio de la Creación",
        "Colegio de la Elocuencia",
        "Colegio de las Espadas",
        "Colegio de los Susurros",
        "Colegio de los Espíritus",
        "Colegio de la Tragedia"
      ],
      cleric: [
        "Dominio del Conocimiento",
        "Dominio del Engaño",
        "Dominio de la Guerra",
        "Dominio de la Luz",
        "Dominio de la Naturaleza",
        "Dominio de la Tempestad",
        "Dominio de la Vida",
        "Dominio de la Muerte",
        "Dominio de la Paz",
        "Dominio del Crepúsculo",
        "Dominio del Orden",
        "Dominio de la Forja",
        "Dominio de la Sepultura",
        "Dominio de la Sangre",
        "Dominio de la Luna"
      ],
      druid: [
        "Círculo de la Tierra",
        "Círculo de la Luna",
        "Círculo de las Esporas",
        "Círculo de las Estrellas",
        "Círculo del Fuego Salvaje",
        "Círculo de los Sueños",
        "Círculo del Pastor",
        "Círculo de los Marchitos",
        "Círculo del Mar"
      ],
      fighter: [
        "Campeón",
        "Maestro del Combate",
        "Caballero Arcano",
        "Caballero Rúnico",
        "Guerrero Psiónico",
        "Arquero Arcano",
        "Caballero",
        "Samurai",
        "Caballero del Eco"
      ],
      monk: [
        "Camino de la Mano Abierta",
        "Camino de la Sombra",
        "Camino de los Cuatro Elementos",
        "Camino de la Misericordia",
        "Camino del Yo Astral",
        "Camino del Maestro Borracho",
        "Camino del Kensei",
        "Camino del Alma Solar",
        "Camino del Alma de Cobalto"
      ],
      paladin: [
        "Juramento de Entrega",
        "Juramento de los Antiguos",
        "Juramento de Venganza",
        "Rompejuramentos",
        "Juramento de Gloria",
        "Juramento de los Vigilantes",
        "Juramento de Conquista",
        "Juramento de Redención",
        "Juramento del Mar Abierto"
      ],
      ranger: [
        "Cazador",
        "Señor de las Bestias",
        "Errante Feérico",
        "Guardaenjambres",
        "Acechador de la Penumbra",
        "Caminante del Horizonte",
        "Cazador de Monstruos"
      ],
      rogue: [
        "Ladrón",
        "Embaucador Arcano",
        "Asesino",
        "Fantasma",
        "Rebanaalmas",
        "Inquisitivo",
        "Mente Maestra",
        "Batidor",
        "Espadachín"
      ],
      sorcerer: [
        "Linaje Dracónico",
        "Magia Salvaje",
        "Alma Mecánica",
        "Mente Aberrante",
        "Alma Divina",
        "Magia de las Sombras",
        "Hechicería de la Tormenta",
        "Runaestirpe"
      ],
      warlock: [
        "El Infernal",
        "El Primigenio",
        "El Señor Feérico",
        "El Genio",
        "El Insondable",
        "El Celestial",
        "El Filo Maléfico",
        "El Muerto Viviente"
      ],
      wizard: [
        "Escuela de Abjuración",
        "Escuela de Adivinación",
        "Escuela de Conjuración",
        "Escuela de Encantamiento",
        "Escuela de Evocación",
        "Escuela de Nigromancia",
        "Escuela de Ilusionismo",
        "Escuela de Transmutación",
        "Canto de la Hoja",
        "Orden de los Escribas",
        "Magia de Guerra",
        "Escuela de Graviturgia",
        "Escuela de Cronoturgia",
        "Magia de Sangre",
        "Dunamancia"
      ],
      artificer: ["Alquimista", "Armero", "Artillero", "Herrero de Batalla"]
    },

    origin: [
      "Acólito",
      "Animador",
      "Gladiador",
      "Artesano Gremial",
      "Comerciante Gremial",
      "Charlatán",
      "Criminal",
      "Espía",
      "Ermitaño",
      "Erudito",
      "Héroe del Pueblo",
      "Huérfano",
      "Marinero",
      "Pirata",
      "Noble",
      "Caballero",
      "Salvaje",
      "Soldado",
      "Campesino",
      "Escriba",
      "Guardia",
      "Guía",
      "Vagabundo",
      "Atormentado",
      "Investigador",
      "Ashari",
      "Agente de la Garra",
      "Erudito del Liceo",
      "Sectario reformado",
      "Cuerpo de Rifles de Piedrablanca",
      "Sonriente",
      "Agente Volstrucker",
      "Cartomante",
      "Recompensado",
      "Arruinado"
    ],
    species: [
      "Enano de las colinas",
      "Enano de las montañas",
      "Alto elfo",
      "Elfo de los bosques (Silvano)",
      "Elfo oscuro (Drow)",
      "Elfo Shadar-Kai",
      "Mediano piesligeros",
      "Mediano fornido",
      "Humano",
      "Humano variante",
      "Dracónido azul",
      "Dracónido blanco",
      "Dracónido bronce",
      "Dracónido cobre",
      "Dracónido negro",
      "Dracónido oro",
      "Dracónido oropel",
      "Dracónido plata",
      "Dracónido rojo",
      "Dracónido verde",
      "Gnomo de los bosques",
      "Gnomo de las rocas",
      "Semielfo",
      "Semiorco",
      "Orco",
      "Tiefling de Asmodeus",
      "Tiefling de Baalzebul",
      "Tiefling de Dispater",
      "Tiefling de Fierna",
      "Tiefling de Glasya",
      "Tiefling de Levistus",
      "Tiefling de Mammon",
      "Tiefling de Mephistopheles",
      "Tiefling de Zariel",
      "Tiefling",
      "Protector Aasimar",
      "Azote Aasimar",
      "Aasimar Caído",
      "Kobold",
      "Goblin",
      "Firbolg",
      "Goliat",
      "Hombre lagarto",
      "Kenku",
      "Tabaxi",
      "Tritón",
      "Aarakocra",
      "Cambiante",
      "Centauro",
      "Duergar",
      "Eladrín",
      "Elfo marino",
      "Genasí de agua",
      "Genasí de aire",
      "Genasí de fuego",
      "Genasí de tierra",
      "Githyanki",
      "Githzerai",
      "Gnomo de las profundidades",
      "Hada",
      "Hobgoblin",
      "Liebrén",
      "Minotauro",
      "Osgo",
      "Replicante",
      "Sátiro",
      "Tortoga",
      "Yuan-ti",
      "Dhampiro",
      "Renacido",
      "Sangre Maléfica",
      "Vacío"
    ],
    traits: [
      "Humor como escudo",
      "Observador silencioso",
      "Directo y brusco",
      "Leal hasta el final",
      "Desconfía de la autoridad",
      "Curioso sin límites",
      "Orgulloso de su linaje",
      "Impulsivo y temerario",
      "Paciente estratega",
      "Protector de los débiles",
      "Ambicioso sin disimulo",
      "Reservado y cauteloso",
      "Sarcástico constante",
      "Optimista incorregible",
      "Pesimista realista",
      "Busca redención",
      "Amante del riesgo",
      "Honorable a toda costa",
      "Manipulador sutil",
      "Competitivo extremo",
      "Espiritual y reflexivo",
      "Materialista declarado",
      "Rencoroso persistente",
      "Valiente en exceso",
      "Calculador frío",
      "Ingenuo y confiado",
      "Vengativo silencioso",
      "Disciplinado férreo",
      "Soñador idealista",
      "Pragmático absoluto",
      "Rebelde por naturaleza",
      "Protector territorial",
      "Carismático natural",
      "Introvertido analítico",
      "Extrovertido teatral",
      "Metódico obsesivo",
      "Improvisador nato",
      "Busca gloria eterna",
      "Evita conflictos",
      "Provocador constante",
      "Altruista genuino",
      "Supersticioso marcado",
      "Escéptico radical",
      "Sonríe mientras miente",
      "Encantador interesado",
      "Guarda secretos peligrosos",
      "Disfruta manipulando",
      "Siempre tiene un plan oculto",
      "Confía solo en sí mismo",
      "Busca poder discretamente",
      "Celoso de su reputación",
      "Habla con medias verdades",
      "Seductor calculador",
      "Desprecia la debilidad",
      "Obsesionado con el control",
      "Ambición disfrazada de nobleza",
      "Finge empatía",
      "Teme perder estatus",
      "Adicto al reconocimiento",
      "Utiliza el miedo como herramienta",
      "Competitivo hasta la traición",
      "Carismático pero frío",
      "Le gusta provocar tensión",
      "Humor incómodo constante",
      "Exagera sus hazañas",
      "Drama innecesario frecuente",
      "Coquetea incluso en peligro",
      "Se ofende con facilidad",
      "Sarcasmo venenoso",
      "Leal mientras convenga",
      "Calcula cada palabra",
      "Busca favores constantemente",
      "Recuerda cada insulto",
      "Disfruta sembrando dudas",
      "Juega con la información",
      "Vive de las apariencias",
      "Se victimiza estratégicamente",
      "Admira a los villanos",
      "Ríe en momentos inapropiados",
      "Provoca rivalidades",
      "Siempre quiere la última palabra",
      "Promete más de lo que cumple",
      "Trata todo como negociación"
    ],
    ideals: [
      "Justicia",
      "Libertad",
      "Tradición",
      "Honor",
      "Valor",
      "Sacrificio",
      "Protección",
      "Lealtad",
      "Gloria",
      "Redención",
      "Esperanza",
      "Equilibrio",
      "Sabiduría",
      "Verdad",
      "Compasión",
      "Unidad",
      "Responsabilidad",
      "Coraje",
      "Destino",
      "Fe",
      "Superación",
      "Perseverancia",
      "Solidaridad",
      "Legado",
      "Nobleza",
      "Orden",
      "Armonía",
      "Disciplina",
      "Altruismo",
      "Descubrimiento",
      "Aventura",
      "Conocimiento",
      "Determinación",
      "Resistencia",
      "Heroísmo",
      "Defensa",
      "Confianza",
      "Honor familiar",
      "Justicia divina",
      "Protección de los inocentes",
      "Ambición",
      "Poder",
      "Control",
      "Influencia",
      "Dominio",
      "Supervivencia",
      "Venganza",
      "Reputación",
      "Riqueza",
      "Prestigio",
      "Pragmatismo",
      "Manipulación",
      "Superioridad",
      "Independencia absoluta",
      "Fama",
      "Temor",
      "Orden impuesto",
      "Obediencia",
      "Secreto",
      "Eficiencia",
      "Resultados a cualquier precio",
      "Equilibrio forzado",
      "Autopreservación",
      "Prueba de fuerza",
      "Competencia",
      "Determinismo",
      "Destino personal",
      "Interés propio",
      "Respeto ganado por miedo",
      "Meritocracia extrema",
      "Ambición desmedida",
      "Gloria personal",
      "Supremacía",
      "Revancha",
      "Control del conocimiento",
      "Autoridad incuestionable",
      "Ventaja estratégica",
      "Pragmatismo frío",
      "Equilibrio mediante sacrificio",
      "Orden sobre libertad"
    ],
    bonds: [
      "Una promesa",
      "Una reliquia familiar",
      "Una deuda de honor",
      "Mi mentor desaparecido",
      "Mi familia",
      "Un juramento sagrado",
      "Mi tierra natal",
      "Un compañero caído",
      "Un antiguo maestro",
      "Una profecía",
      "Un legado familiar",
      "Mi orden o gremio",
      "Un amigo de la infancia",
      "Un amor perdido",
      "Mi deidad",
      "Una misión inconclusa",
      "Un hermano o hermana",
      "Mi grupo de aventuras",
      "Una causa justa",
      "Un pupilo bajo mi tutela",
      "Un mapa heredado",
      "Una espada ancestral",
      "Un voto de protección",
      "Un pueblo que me acogió",
      "Una visión divina",
      "Un dragón derrotado",
      "Un secreto compartido",
      "Una carta sin entregar",
      "Un símbolo sagrado",
      "Una hermandad",
      "Un favor pendiente",
      "Un tratado de paz",
      "Un estandarte familiar",
      "Un aprendiz prometedor",
      "Un juramento de sangre",
      "Un pacto honorable",
      "Un reino que proteger",
      "Un ideal transmitido por mis padres",
      "Un aliado fiel",
      "Una misión divina",
      "Una deuda impagable",
      "Un pacto oscuro",
      "Un secreto vergonzoso",
      "Un crimen del pasado",
      "Una traición cometida",
      "Un enemigo personal",
      "Una maldición familiar",
      "Un contrato vinculante",
      "Una identidad falsa",
      "Un chantaje constante",
      "Una promesa rota",
      "Un poder prohibido",
      "Una reliquia robada",
      "Un culto secreto",
      "Una ambición compartida",
      "Un antiguo rival",
      "Un demonio al que debo algo",
      "Un error irreparable",
      "Un juramento forzado",
      "Una sombra del pasado",
      "Un familiar corrupto",
      "Un benefactor sospechoso",
      "Una orden cuestionable",
      "Un pacto de silencio",
      "Un artefacto peligroso",
      "Un secreto que destruiría mi reputación",
      "Un experimento fallido",
      "Un nombre que oculto",
      "Una traición sufrida",
      "Un destino impuesto",
      "Un enemigo que me perdonó",
      "Un aliado poco fiable",
      "Una deuda con un criminal",
      "Un libro prohibido",
      "Un pasado inventado",
      "Una promesa hecha bajo coacción",
      "Un amor manipulador",
      "Una venganza pendiente",
      "Un maestro cruel",
      "Una verdad que debo ocultar"
    ],
    flaws: [
      "Orgullo",
      "Impulsividad",
      "Obsesión",
      "Arrogancia",
      "Desconfianza",
      "Celos",
      "Envidia",
      "Ira",
      "Pesimismo",
      "Inseguridad",
      "Codicia",
      "Rencor",
      "Terquedad",
      "Ansiedad",
      "Paranoia",
      "Manipulación",
      "Control excesivo",
      "Necesidad de aprobación",
      "Miedo al fracaso",
      "Vengatividad",
      "Fanatismo",
      "Frialdad emocional",
      "Egoísmo",
      "Desprecio",
      "Cinismo",
      "Intolerancia",
      "Impaciencia",
      "Negación",
      "Dependencia emocional",
      "Victimismo",
      "Competitividad tóxica",
      "Perfeccionismo",
      "Autoengaño",
      "Desorganización",
      "Indecisión",
      "Temor al abandono",
      "Ambición desmedida",
      "Falta de empatía",
      "Deshonestidad",
      "Deslealtad",
      "Falta de una pierna",
      "Falta de un brazo",
      "Tartamudez",
      "Claustrofobia",
      "Miedo a la oscuridad",
      "Insomnio crónico",
      "Cicatriz desfigurante",
      "Falta de un ojo",
      "Mano temblorosa",
      "Sordera parcial",
      "Cojea ligeramente",
      "Pérdida de memoria reciente",
      "Fobia al fuego",
      "Fobia a la sangre",
      "Adicción al alcohol",
      "Adicción al juego",
      "Enfermedad crónica",
      "Visión deficiente",
      "Voz extremadamente baja",
      "Risa nerviosa incontrolable",
      "Sudoración excesiva",
      "Dolor constante en una antigua herida",
      "Migrañas frecuentes",
      "Falta de resistencia física",
      "Alergia severa",
      "Pánico escénico",
      "Dificultad para mentir",
      "Incapacidad para guardar secretos",
      "Incapacidad para nadar",
      "Torpeza extrema",
      "Reflejos lentos",
      "Dolor al usar magia",
      "Dependencia de medicación",
      "Amnesia parcial",
      "Vértigo",
      "Pesadillas constantes",
      "Problemas de concentración",
      "Manía nerviosa repetitiva",
      "Falta de sentido del humor",
      "Incapacidad para rechazar desafíos",
      "Debilidad en combate prolongado",
      "Respiración dificultosa"
    ]
  },

  en: {
    classes: [
      { id: "barbarian", name: "Barbarian" },
      { id: "bard", name: "Bard" },
      { id: "cleric", name: "Cleric" },
      { id: "druid", name: "Druid" },
      { id: "fighter", name: "Fighter" },
      { id: "monk", name: "Monk" },
      { id: "paladin", name: "Paladin" },
      { id: "ranger", name: "Ranger" },
      { id: "rogue", name: "Rogue" },
      { id: "sorcerer", name: "Sorcerer" },
      { id: "warlock", name: "Warlock" },
      { id: "wizard", name: "Wizard" },
      { id: "artificer", name: "Artificer" }
    ],

    subclassesByClass: {
      barbarian: [
        "Path of the Berserker",
        "Path of the Totem Warrior",
        "Path of the Beast",
        "Path of the Wild Magic",
        "Path of the Ancestral Guardian",
        "Path of the Zealot",
        "Path of the Storm Herald",
        "Path of the Juggernaut",
        "Path of the Wild Heart",
        "Path of the World Tree",
        "Path of the Giant"
      ],
      bard: [
        "College of Lore",
        "College of Valor",
        "College of Dance",
        "College of Glamour",
        "College of Creation",
        "College of Eloquence",
        "College of Swords",
        "College of Whispers",
        "College of Spirits",
        "College of Tragedy"
      ],
      cleric: [
        "Knowledge Domain",
        "Trickery Domain",
        "War Domain",
        "Light Domain",
        "Nature Domain",
        "Tempest Domain",
        "Life Domain",
        "Death Domain",
        "Peace Domain",
        "Twilight Domain",
        "Order Domain",
        "Forge Domain",
        "Grave Domain",
        "Blood Domain",
        "Moon Domain"
      ],
      druid: [
        "Circle of the Land",
        "Circle of the Moon",
        "Circle of Spores",
        "Circle of the Stars",
        "Circle of Wildfire",
        "Circle of Dreams",
        "Circle of the Shepherd",
        "Circle of the Blighted",
        "Circle of the Sea"
      ],
      fighter: [
        "Champion",
        "Battle Master",
        "Eldritch Knight",
        "Rune Knight",
        "Psi Warrior",
        "Arcane Archer",
        "Cavalier",
        "Samurai",
        "Echo Knight"
      ],
      monk: [
        "Way of the Open Hand",
        "Way of Shadow",
        "Way of the Four Elements",
        "Way of Mercy",
        "Way of the Astral Self",
        "Way of the Drunken Master",
        "Way of the Kensei",
        "Way of the Sun Soul",
        "Way of the Cobalt Soul"
      ],
      paladin: [
        "Oath of Devotion",
        "Oath of the Ancients",
        "Oath of Vengeance",
        "Oathbreaker",
        "Oath of Glory",
        "Oath of the Watchers",
        "Oath of Conquest",
        "Oath of Redemption",
        "Oath of the Open Sea"
      ],
      ranger: [
        "Hunter",
        "Beast Master",
        "Fey Wanderer",
        "Swarmkeeper",
        "Gloom Stalker",
        "Horizon Walker",
        "Monster Slayer"
      ],
      rogue: [
        "Thief",
        "Arcane Trickster",
        "Assassin",
        "Phantom",
        "Soulknife",
        "Inquisitive",
        "Mastermind",
        "Scout",
        "Swashbuckler"
      ],
      sorcerer: [
        "Draconic Bloodline",
        "Wild Magic",
        "Clockwork Soul",
        "Aberrant Mind",
        "Divine Soul",
        "Shadow Magic",
        "Storm Sorcery",
        "Runechild"
      ],
      warlock: [
        "The Fiend",
        "The Great Old One",
        "The Archfey",
        "The Genie",
        "The Fathomless",
        "The Celestial",
        "The Hexblade",
        "The Undead"
      ],
      wizard: [
        "School of Abjuration",
        "School of Divination",
        "School of Conjuration",
        "School of Enchantment",
        "School of Evocation",
        "School of Necromancy",
        "School of Illusion",
        "School of Transmutation",
        "Bladesinging",
        "Order of Scribes",
        "War Magic",
        "Graviturgy Magic",
        "Chronurgy Magic",
        "Blood Magic",
        "Dunamancy"
      ],
      artificer: ["Alchemist", "Armorer", "Artillerist", "Battle Smith"]
    },

    origin: [
      "Acolyte",
      "Entertainer",
      "Gladiator",
      "Guild Artisan",
      "Guild Merchant",
      "Charlatan",
      "Criminal",
      "Spy",
      "Hermit",
      "Sage",
      "Folk Hero",
      "Urchin",
      "Sailor",
      "Pirate",
      "Noble",
      "Knight",
      "Outlander",
      "Soldier",
      "Farmer",
      "Scribe",
      "Guard",
      "Guide",
      "Wayfarer",
      "Haunted One",
      "Investigator",
      "Ashari",
      "Clasp Agent",
      "Lyceum Scholar",
      "Reformed Cultist",
      "Whitestone Rifle Corps",
      "Grinner",
      "Volstrucker Agent",
      "Cartomancer",
      "Rewarded",
      "Ruined"
    ],
    species: [
      "Hill Dwarf",
      "Mountain Dwarf",
      "High Elf",
      "Wood Elf (Sylvan)",
      "Dark Elf (Drow)",
      "Shadar-Kai Elf",
      "Lightfoot Halfling",
      "Stout Halfling",
      "Human",
      "Variant Human",
      "Blue Dragonborn",
      "White Dragonborn",
      "Bronze Dragonborn",
      "Copper Dragonborn",
      "Black Dragonborn",
      "Gold Dragonborn",
      "Brass Dragonborn",
      "Silver Dragonborn",
      "Red Dragonborn",
      "Green Dragonborn",
      "Forest Gnome",
      "Rock Gnome",
      "Half-Elf",
      "Half-Orc",
      "Orc",
      "Asmodeus Tiefling",
      "Baalzebul Tiefling",
      "Dispater Tiefling",
      "Fierna Tiefling",
      "Glasya Tiefling",
      "Levistus Tiefling",
      "Mammon Tiefling",
      "Mephistopheles Tiefling",
      "Zariel Tiefling",
      "Tiefling",
      "Protector Aasimar",
      "Scourge Aasimar",
      "Fallen Aasimar",
      "Kobold",
      "Goblin",
      "Firbolg",
      "Goliath",
      "Lizardfolk",
      "Kenku",
      "Tabaxi",
      "Triton",
      "Aarakocra",
      "Shifter",
      "Centaur",
      "Duergar",
      "Eladrin",
      "Sea Elf",
      "Water Genasi",
      "Air Genasi",
      "Fire Genasi",
      "Earth Genasi",
      "Githyanki",
      "Githzerai",
      "Deep Gnome",
      "Fairy",
      "Hobgoblin",
      "Harengon",
      "Minotaur",
      "Bugbear",
      "Changeling",
      "Satyr",
      "Tortle",
      "Yuan-ti",
      "Dhampir",
      "Reborn",
      "Hexblood",
      "Hollow One"
    ],
    traits: [
      "Uses humor as a shield",
      "Quiet observer",
      "Blunt honesty",
      "Loyal to the end",
      "Distrusts authority",
      "Endlessly curious",
      "Proud of their lineage",
      "Impulsive and reckless",
      "Patient strategist",
      "Protector of the weak",
      "Openly ambitious",
      "Reserved and cautious",
      "Constantly sarcastic",
      "Incorrigible optimist",
      "Realistic pessimist",
      "Seeking redemption",
      "Thrill seeker",
      "Honorable at all costs",
      "Subtle manipulator",
      "Extremely competitive",
      "Spiritual and reflective",
      "Open materialist",
      "Holds grudges",
      "Overly brave",
      "Cold and calculating",
      "Naive and trusting",
      "Quietly vengeful",
      "Strictly disciplined",
      "Idealistic dreamer",
      "Pure pragmatist",
      "Natural rebel",
      "Territorial protector",
      "Naturally charismatic",
      "Analytical introvert",
      "Theatrical extrovert",
      "Methodically obsessive",
      "Born improviser",
      "Seeks eternal glory",
      "Avoids conflict",
      "Constant provocateur",
      "Genuinely altruistic",
      "Deeply superstitious",
      "Radical skeptic",
      "Smiles while lying",
      "Self-serving charmer",
      "Keeps dangerous secrets",
      "Enjoys manipulation",
      "Always has a hidden plan",
      "Trusts no one but themselves",
      "Seeks power quietly",
      "Jealous of their reputation",
      "Speaks in half-truths",
      "Calculating seducer",
      "Despises weakness",
      "Obsessed with control",
      "Ambition masked as virtue",
      "Feigns empathy",
      "Fears losing status",
      "Addicted to recognition",
      "Uses fear as a tool",
      "Competitive to betrayal",
      "Charismatic yet cold",
      "Enjoys stirring tension",
      "Constant awkward humor",
      "Exaggerates achievements",
      "Creates unnecessary drama",
      "Flirts even in danger",
      "Easily offended",
      "Venomous sarcasm",
      "Loyal when convenient",
      "Weighs every word",
      "Constantly seeks favors",
      "Never forgets an insult",
      "Enjoys planting doubt",
      "Plays with information",
      "Lives for appearances",
      "Strategic victim",
      "Admires villains",
      "Laughs at the wrong time",
      "Provokes rivalries",
      "Needs the last word",
      "Overpromises regularly",
      "Treats everything as a negotiation"
    ],
    ideals: [
      "Justice",
      "Freedom",
      "Tradition",
      "Honor",
      "Courage",
      "Sacrifice",
      "Protection",
      "Loyalty",
      "Glory",
      "Redemption",
      "Hope",
      "Balance",
      "Wisdom",
      "Truth",
      "Compassion",
      "Unity",
      "Responsibility",
      "Bravery",
      "Destiny",
      "Faith",
      "Self-improvement",
      "Perseverance",
      "Solidarity",
      "Legacy",
      "Nobility",
      "Order",
      "Harmony",
      "Discipline",
      "Altruism",
      "Discovery",
      "Adventure",
      "Knowledge",
      "Determination",
      "Endurance",
      "Heroism",
      "Defense",
      "Trust",
      "Family honor",
      "Divine justice",
      "Protection of the innocent",
      "Ambition",
      "Power",
      "Control",
      "Influence",
      "Domination",
      "Survival",
      "Revenge",
      "Reputation",
      "Wealth",
      "Prestige",
      "Pragmatism",
      "Manipulation",
      "Superiority",
      "Absolute independence",
      "Fame",
      "Fear",
      "Enforced order",
      "Obedience",
      "Secrecy",
      "Efficiency",
      "Results at any cost",
      "Forced balance",
      "Self-preservation",
      "Trial by strength",
      "Competition",
      "Determinism",
      "Personal destiny",
      "Self-interest",
      "Respect through fear",
      "Extreme meritocracy",
      "Unchecked ambition",
      "Personal glory",
      "Supremacy",
      "Retribution",
      "Control of knowledge",
      "Unquestioned authority",
      "Strategic advantage",
      "Cold pragmatism",
      "Balance through sacrifice",
      "Order over freedom"
    ],
    bonds: [
      "A promise",
      "A family relic",
      "A debt of honor",
      "My missing mentor",
      "My family",
      "A sacred oath",
      "My homeland",
      "A fallen companion",
      "An old teacher",
      "A prophecy",
      "A family legacy",
      "My order or guild",
      "A childhood friend",
      "A lost love",
      "My deity",
      "An unfinished mission",
      "A sibling",
      "My adventuring party",
      "A just cause",
      "A protégé under my care",
      "An inherited map",
      "An ancestral sword",
      "A vow of protection",
      "A village that sheltered me",
      "A divine vision",
      "A dragon I defeated",
      "A shared secret",
      "An undelivered letter",
      "A sacred symbol",
      "A brotherhood",
      "A favor owed",
      "A peace treaty",
      "A family banner",
      "A promising apprentice",
      "A blood oath",
      "An honorable pact",
      "A kingdom to protect",
      "An ideal taught by my parents",
      "A loyal ally",
      "A divine mission",
      "An unpayable debt",
      "A dark pact",
      "A shameful secret",
      "A past crime",
      "A betrayal I committed",
      "A personal enemy",
      "A family curse",
      "A binding contract",
      "A false identity",
      "Ongoing blackmail",
      "A broken promise",
      "Forbidden power",
      "A stolen relic",
      "A secret cult",
      "A shared ambition",
      "An old rival",
      "A demon I owe",
      "An irreparable mistake",
      "A forced oath",
      "A shadow from my past",
      "A corrupt relative",
      "A suspicious benefactor",
      "A questionable order",
      "A pact of silence",
      "A dangerous artifact",
      "A reputation-shattering secret",
      "A failed experiment",
      "A hidden name",
      "A betrayal I suffered",
      "An imposed destiny",
      "An enemy who spared me",
      "An unreliable ally",
      "A debt to a criminal",
      "A forbidden tome",
      "A fabricated past",
      "A promise made under duress",
      "A manipulative love",
      "An unfinished revenge",
      "A cruel master",
      "A truth I must hide"
    ],
    flaws: [
      "Pride",
      "Impulsiveness",
      "Obsession",
      "Arrogance",
      "Mistrust",
      "Jealousy",
      "Envy",
      "Wrath",
      "Pessimism",
      "Insecurity",
      "Greed",
      "Resentment",
      "Stubbornness",
      "Anxiety",
      "Paranoia",
      "Manipulativeness",
      "Controlling nature",
      "Need for approval",
      "Fear of failure",
      "Vindictiveness",
      "Fanaticism",
      "Emotional detachment",
      "Selfishness",
      "Contempt",
      "Cynicism",
      "Intolerance",
      "Impatience",
      "Denial",
      "Emotional dependency",
      "Victim mentality",
      "Toxic competitiveness",
      "Perfectionism",
      "Self-deception",
      "Disorganization",
      "Indecisiveness",
      "Fear of abandonment",
      "Excessive ambition",
      "Lack of empathy",
      "Dishonesty",
      "Disloyalty",
      "Missing a leg",
      "Missing an arm",
      "Stutter",
      "Claustrophobia",
      "Fear of the dark",
      "Chronic insomnia",
      "Disfiguring scar",
      "Missing an eye",
      "Shaky hands",
      "Partial deafness",
      "Slight limp",
      "Short-term memory loss",
      "Fear of fire",
      "Fear of blood",
      "Alcohol addiction",
      "Gambling addiction",
      "Chronic illness",
      "Poor eyesight",
      "Extremely soft voice",
      "Uncontrollable nervous laughter",
      "Excessive sweating",
      "Persistent old wound pain",
      "Frequent migraines",
      "Low physical stamina",
      "Severe allergy",
      "Stage fright",
      "Unable to lie",
      "Unable to keep secrets",
      "Cannot swim",
      "Extreme clumsiness",
      "Slow reflexes",
      "Pain when casting magic",
      "Medication dependency",
      "Partial amnesia",
      "Vertigo",
      "Recurring nightmares",
      "Difficulty concentrating",
      "Repetitive nervous habit",
      "No sense of humor",
      "Unable to refuse challenges",
      "Weak in prolonged combat",
      "Labored breathing"
    ]
  }
};

export const SECTIONS = [
  { key: "class", label_es: "Clase", label_en: "Class" },
  { key: "subclass", label_es: "Subclase", label_en: "Subclass" },
  { key: "origin", label_es: "Trasfondo/Origen", label_en: "Background/Origin" },
  { key: "species", label_es: "Raza/Especie", label_en: "Race/Species" },
  { key: "traits", label_es: "Rasgos de personalidad", label_en: "Personality traits" },
  { key: "ideals", label_es: "Ideales", label_en: "Ideals" },
  { key: "bonds", label_es: "Vínculos", label_en: "Bonds" },
  { key: "flaws", label_es: "Defectos", label_en: "Flaws" }
];
